services:
  mysql-db:
    container_name: mysql-db
    image: mysql:8.4.6
    ports:
      - "3306:3306"
    networks:
      - my-app-network
    environment:
      - MYSQL_DATABASE=walletslotdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=dnxlachl
      - MYSQL_ROOT_PASSWORD=dnxlachl
    volumes:
      - ./mysql-data:/var/lib/mysql

  backend-app:
    container_name: backend-app
    image: registry.gitlab.com/S13P21B108/backend-app-image:latest
    depends_on:
      - mysql-db
    networks:
      - my-app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/walletslotdb?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=dnxlachl

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-app-network

# 서비스들이 사용할 네트워크
networks:
  my-app-network:
    driver: bridge
