spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3306/walletslotdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none              # ✅ 테스트도 DDL 미수행(원하면 임시로 update로 바꿔도 됨)

springdoc:
  swagger-ui:
    path: /swagger-ui

cloud:
  aws:
    region: ap-northeast-2

app:
  security:
    jwt:
      secret_b64: ${JWT_SECRET_B64:}

    pepper:
      cipher:
        v2025_01: ${PEPPER_CIPHER_V2025_01:}
        v2024_12: ${PEPPER_CIPHER_V2024_12:}

    bcrypt:
      cost: 12
